version = "1"

name = "Demo Macro"
description = "Macro to demonstrate DeepSource Macros"
category = "language"
visibility = "public"

[analyzer]
  command = "python /app/main.py"

[build]
  image = "alpine:3.15"
  steps = """cp -r . /app
  apk add shadow git grep"""
